export const AUDIT_ACTIONS = {
  PROMOTE_ADMIN: 'PROMOTE_ADMIN',
  DEMOTE_ADMIN: 'DEMOTE_ADMIN',
  DEMOTE_BLOCKED_SUPER_ADMIN: 'DEMOTE_BLOCKED_SUPER_ADMIN',
  DEACTIVATE_BLOCKED_SUPER_ADMIN: 'DEACTIVATE_BLOCKED_SUPER_ADMIN',
  DEACTIVATE_USER: 'DEACTIVATE_USER',
  ACTIVATE_USER: 'ACTIVATE_USER',
  PLACE_APPROVED: 'PLACE_APPROVED',
  PLACE_REJECTED: 'PLACE_REJECTED',
  PLACE_UPDATED: 'PLACE_UPDATED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
