export enum ErrorCode {
  // Auth
  AUTH_ACCOUNT_DEACTIVATED = 'AUTH_ACCOUNT_DEACTIVATED',
  AUTH_ALREADY_COMPLETED_TODAY = 'AUTH_ALREADY_COMPLETED_TODAY',
  AUTH_DAILY_SEND_LIMIT_EXCEEDED = 'AUTH_DAILY_SEND_LIMIT_EXCEEDED',
  AUTH_EMAIL_ALREADY_REGISTERED = 'AUTH_EMAIL_ALREADY_REGISTERED',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_EMAIL_IN_USE = 'AUTH_EMAIL_IN_USE',
  AUTH_EMAIL_NOT_REGISTERED = 'AUTH_EMAIL_NOT_REGISTERED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_INVALID_VERIFICATION_CODE = 'AUTH_INVALID_VERIFICATION_CODE',
  AUTH_NO_REREGISTER_ACCOUNT = 'AUTH_NO_REREGISTER_ACCOUNT',
  AUTH_PASSWORD_CHANGE_LIMIT = 'AUTH_PASSWORD_CHANGE_LIMIT',
  AUTH_RE_REGISTER_ERROR = 'AUTH_RE_REGISTER_ERROR',
  AUTH_RE_REGISTER_NOT_AVAILABLE = 'AUTH_RE_REGISTER_NOT_AVAILABLE',
  AUTH_SOCIAL_LOGIN_ACCOUNT = 'AUTH_SOCIAL_LOGIN_ACCOUNT',
  AUTH_VERIFICATION_BLOCKED = 'AUTH_VERIFICATION_BLOCKED',
  AUTH_VERIFICATION_CODE_EXPIRED = 'AUTH_VERIFICATION_CODE_EXPIRED',
  AUTH_VERIFICATION_CODE_INVALID = 'AUTH_VERIFICATION_CODE_INVALID',
  AUTH_VERIFICATION_CODE_INVALIDATED = 'AUTH_VERIFICATION_CODE_INVALIDATED',
  AUTH_VERIFICATION_CODE_USED = 'AUTH_VERIFICATION_CODE_USED',
  AUTH_VERIFICATION_TOO_MANY_REQUESTS = 'AUTH_VERIFICATION_TOO_MANY_REQUESTS',
  AUTH_WITHDRAWAL_HISTORY_CONFIRM = 'AUTH_WITHDRAWAL_HISTORY_CONFIRM',
  AUTH_WITHDRAWAL_HISTORY_REREGISTER = 'AUTH_WITHDRAWAL_HISTORY_REREGISTER',

  // User
  USER_ALREADY_WITHDRAWN = 'USER_ALREADY_WITHDRAWN',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_MAX_ADDRESSES_EXCEEDED = 'USER_MAX_ADDRESSES_EXCEEDED',
  USER_ADDRESS_NOT_FOUND = 'USER_ADDRESS_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Address
  ADDRESS_CANNOT_DELETE_DEFAULT = 'ADDRESS_CANNOT_DELETE_DEFAULT',
  ADDRESS_LAT_LNG_REQUIRED = 'ADDRESS_LAT_LNG_REQUIRED',
  ADDRESS_MAX_LIMIT = 'ADDRESS_MAX_LIMIT',
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
  ADDRESS_NO_ID_TO_DELETE = 'ADDRESS_NO_ID_TO_DELETE',
  ADDRESS_UPDATE_FAILED = 'ADDRESS_UPDATE_FAILED',

  // Menu
  MENU_DEFAULT_ADDRESS_REQUIRED = 'MENU_DEFAULT_ADDRESS_REQUIRED',
  MENU_EMPTY = 'MENU_EMPTY',
  MENU_HISTORY_NOT_FOUND = 'MENU_HISTORY_NOT_FOUND',
  MENU_HISTORY_OWNERSHIP_REQUIRED = 'MENU_HISTORY_OWNERSHIP_REQUIRED',
  MENU_INVALID_HISTORY_ID = 'MENU_INVALID_HISTORY_ID',
  MENU_INVALID_SELECTION_ID = 'MENU_INVALID_SELECTION_ID',
  MENU_NAME_REQUIRED = 'MENU_NAME_REQUIRED',
  MENU_RECOMMENDATION_ID_REQUIRED = 'MENU_RECOMMENDATION_ID_REQUIRED',
  MENU_SELECTION_NOT_FOUND = 'MENU_SELECTION_NOT_FOUND',

  // Place
  PLACE_ALREADY_RECOMMENDED = 'PLACE_ALREADY_RECOMMENDED',
  PLACE_AI_RECOMMENDATION_FAILED = 'PLACE_AI_RECOMMENDATION_FAILED',
  PLACE_SEARCH_NO_RESULTS = 'PLACE_SEARCH_NO_RESULTS',

  // Notification
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

  // Bug report
  BUG_REPORT_NOT_FOUND = 'BUG_REPORT_NOT_FOUND',

  // Admin
  ADMIN_USER_ALREADY_ACTIVATED = 'ADMIN_USER_ALREADY_ACTIVATED',
  ADMIN_USER_ALREADY_DEACTIVATED = 'ADMIN_USER_ALREADY_DEACTIVATED',
  ADMIN_USER_NOT_FOUND = 'ADMIN_USER_NOT_FOUND',

  // Search
  SEARCH_NO_RESULTS = 'SEARCH_NO_RESULTS',

  // Location
  LOCATION_ADDRESS_NOT_FOUND = 'LOCATION_ADDRESS_NOT_FOUND',

  // User Place
  USER_PLACE_NOT_FOUND = 'USER_PLACE_NOT_FOUND',
  USER_PLACE_DAILY_LIMIT_EXCEEDED = 'USER_PLACE_DAILY_LIMIT_EXCEEDED',
  USER_PLACE_DUPLICATE_REGISTRATION = 'USER_PLACE_DUPLICATE_REGISTRATION',
  USER_PLACE_NOT_EDITABLE = 'USER_PLACE_NOT_EDITABLE',
  USER_PLACE_NOT_DELETABLE = 'USER_PLACE_NOT_DELETABLE',
  USER_PLACE_RATE_LIMIT_EXCEEDED = 'USER_PLACE_RATE_LIMIT_EXCEEDED',
  USER_PLACE_OPTIMISTIC_LOCK_FAILED = 'USER_PLACE_OPTIMISTIC_LOCK_FAILED',
  USER_PLACE_INVALID_CATEGORY = 'USER_PLACE_INVALID_CATEGORY',
  USER_PLACE_INVALID_STATUS = 'USER_PLACE_INVALID_STATUS',
  USER_PLACE_UNAUTHORIZED = 'USER_PLACE_UNAUTHORIZED',
  USER_PLACE_INVALID_COORDINATES = 'USER_PLACE_INVALID_COORDINATES',
  USER_PLACE_NAME_TOO_LONG = 'USER_PLACE_NAME_TOO_LONG',

  // External
  EXTERNAL_AI_ERROR = 'EXTERNAL_AI_ERROR',
  EXTERNAL_GOOGLE_PLACES_ERROR = 'EXTERNAL_GOOGLE_PLACES_ERROR',

  // General
  CONFIG_MISSING_ERROR = 'CONFIG_MISSING_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
