export enum ErrorCode {
  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_VERIFICATION_CODE = 'AUTH_INVALID_VERIFICATION_CODE',
  AUTH_VERIFICATION_CODE_EXPIRED = 'AUTH_VERIFICATION_CODE_EXPIRED',
  AUTH_SOCIAL_LOGIN_ACCOUNT = 'AUTH_SOCIAL_LOGIN_ACCOUNT',
  AUTH_EMAIL_NOT_REGISTERED = 'AUTH_EMAIL_NOT_REGISTERED',
  AUTH_RE_REGISTER_NOT_AVAILABLE = 'AUTH_RE_REGISTER_NOT_AVAILABLE',
  AUTH_RE_REGISTER_ERROR = 'AUTH_RE_REGISTER_ERROR',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_MAX_ADDRESSES_EXCEEDED = 'USER_MAX_ADDRESSES_EXCEEDED',
  USER_ADDRESS_NOT_FOUND = 'USER_ADDRESS_NOT_FOUND',

  // Menu
  MENU_SELECTION_NOT_FOUND = 'MENU_SELECTION_NOT_FOUND',
  MENU_EMPTY = 'MENU_EMPTY',

  // External
  EXTERNAL_AI_ERROR = 'EXTERNAL_AI_ERROR',
  EXTERNAL_GOOGLE_PLACES_ERROR = 'EXTERNAL_GOOGLE_PLACES_ERROR',

  // General
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  CONFIG_MISSING_ERROR = 'CONFIG_MISSING_ERROR',
}
