/**
 * Success message codes for API responses
 * Format: MODULE_ACTION_STATUS
 */
export enum MessageCode {
  // Auth
  AUTH_EMAIL_VERIFICATION_COMPLETED = 'AUTH_EMAIL_VERIFICATION_COMPLETED',
  AUTH_PASSWORD_RESET_COMPLETED = 'AUTH_PASSWORD_RESET_COMPLETED',
  AUTH_LOGOUT_COMPLETED = 'AUTH_LOGOUT_COMPLETED',
  AUTH_REGISTRATION_COMPLETED = 'AUTH_REGISTRATION_COMPLETED',
  AUTH_RE_REGISTRATION_COMPLETED = 'AUTH_RE_REGISTRATION_COMPLETED',
  AUTH_EMAIL_AVAILABLE = 'AUTH_EMAIL_AVAILABLE',
  AUTH_VERIFICATION_CODE_SENT = 'AUTH_VERIFICATION_CODE_SENT',
  AUTH_EMAIL_CONFIG_MISSING = 'AUTH_EMAIL_CONFIG_MISSING',
  AUTH_EMAIL_CONFIG_ERROR = 'AUTH_EMAIL_CONFIG_ERROR',

  // User
  USER_WITHDRAWAL_COMPLETED = 'USER_WITHDRAWAL_COMPLETED',
  USER_LANGUAGE_CHANGED = 'USER_LANGUAGE_CHANGED',
  USER_ADDRESS_DELETED = 'USER_ADDRESS_DELETED',

  // Notification
  NOTIFICATION_DELETED = 'NOTIFICATION_DELETED',

  // Admin
  ADMIN_USER_DEACTIVATED = 'ADMIN_USER_DEACTIVATED',
  ADMIN_USER_ACTIVATED = 'ADMIN_USER_ACTIVATED',
}

/**
 * Validation message codes for DTO validation
 * Format: VALIDATION_RULE
 */
export enum ValidationCode {
  VALIDATION_REQUIRED = 'VALIDATION_REQUIRED',
  VALIDATION_STRING = 'VALIDATION_STRING',
  VALIDATION_INT = 'VALIDATION_INT',
  VALIDATION_MIN = 'VALIDATION_MIN',
  VALIDATION_MAX = 'VALIDATION_MAX',
  VALIDATION_MAX_LENGTH = 'VALIDATION_MAX_LENGTH',
  VALIDATION_INVALID_ENUM = 'VALIDATION_INVALID_ENUM',
  VALIDATION_BOOLEAN = 'VALIDATION_BOOLEAN',
  VALIDATION_DATE_FORMAT = 'VALIDATION_DATE_FORMAT',
  VALIDATION_ARRAY_MIN = 'VALIDATION_ARRAY_MIN',
  VALIDATION_ARRAY_MAX = 'VALIDATION_ARRAY_MAX',
}
